scalar Long

# ===== Pagination =====
type PageInfo {
    totalPages: Int!
    totalElements: Long!
    number: Int!
    size: Int!
    first: Boolean!
    last: Boolean!
    empty: Boolean!
}

input PageableInput {
    page: Int = 0
    size: Int = 10
    sorts: [String!]  # Format: ["name,asc", "endTime,desc"]
}

# ===== Classroom =====
type ClassroomPage {
    content: [Classroom!]!
    pageInfo: PageInfo!
}

type Classroom {
    id: ID!
    name: String!
    description: String
    type: ClassroomType!
    status: ClassroomStatus!
    instructorId: ID!
    instructor: Instructor
    classCode: String
    endTime: String
    thumbnailUrl: String
    bannerUrl: String
}

type Instructor {
    id: ID!
    name: String!
    username: String!
    avatar: String
}

enum SortDirection {
    ASC
    DESC
}

enum ClassroomType {
    PUBLIC
    PRIVATE
}

enum ClassroomStatus {
    ACTIVE
    CLOSED
    DELETED
}

type Query {
    getClassroomById(id: ID!): Classroom
    getClassroomsByInstructor(instructorId: ID!): [Classroom!]!
    getAllClassrooms: [Classroom]
    getClassroomPageByInstructorId(
        instructorId: ID!
        pageable: PageableInput
    ): ClassroomPage!
}
